# Generated by Django 5.0.7 on 2024-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_remove_job_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=100)),
            ],
        ),
    ]
