# Generated by Django 5.0.7 on 2024-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_delete_salaryinsight_alter_applicant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(default='default_resume.pdf', upload_to='resumes/'),
        ),
    ]
