# Generated by Django 5.0.7 on 2024-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Under Review'), ('3', 'Interview Scheduled'), ('4', 'Offered'), ('5', 'Rejected')], default='1', max_length=1),
        ),
    ]
