# Generated by Django 5.0.7 on 2024-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='Applied', max_length=100),
        ),
    ]
